### ISSUE TITLE
Wrong register

### ISSUE THREAD

**Issue by lucasperovani** [kmani314/ATMega32u4-HID-Keyboard#2]
Hi, you made an excellent repository with a bunch of hard-to-find knowledge based on the USB of atmega32u4. I think, and hope, you still wanna improve it... I found a silly mistake that is easy to pass over and is easy to fix.

In function usb_init (src/usb.c) UDCON is setted to 0. But the DETACH bit is cleared in USBCON. It doesn't impact the functionality of the code (unless you need the VBUS Transition Interrupt). 

```
...
USBCON &= ~(1 << FRZCLK);          // Unfreeze the clock

  UDCON = 0;  // FULL SPEED MODE

  USBCON &= ~(1 << DETACH);  // Connect  <- Bit DETACH being cleared in USBCON, but it was cleared in UDCON
  UDIEN |= (1 << EORSTE) |
           (1 << SOFE);  // Re-enable the EORSTE (End Of Reset) Interrupt so we
                         // know when we can configure the control endpoint
...

```

The line `USBCON &= ~(1 << DETACH);` can be easily removed without any error in the code (I think).

The pages in the [manual](https://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-7766-8-bit-AVR-ATmega16U4-32U4_Datasheet.pdf) that specifies those registers are 267, for USBCON, and 281, for UDCON. I couldn't test it yet, btw.
Nevertheless, I'm grateful for your job and want to thank you! It's pretty hard to find those information in Google!!

**Comment by YellowKll** [comment]
I was going  to report the same "issue".
DETACH doesn't belong to USBCON, but it belongs to UDCON.

**Comment by kmani314** [comment]
No longer have hardware to test this on, but I think you're right based on the datasheet. Thanks!
